### ISSUE TITLE
Port 8888 not opened

### ISSUE THREAD

**Issue by brejoc** [cboylan/zmq-event-publisher#1]
After installing the plugin from updates.jenkins-ci.org and restarting jenkins 1.509.2, there is no server on port 8888. Is there some way to debug this?

**Comment by cboylan** [comment]
I want to say that the ZMQ event publisher doesn't start the ZMQ publisher until the first event happens. If you start a job that should create an event which would open the socket, this would be logged in the jenkins log. I am happy to look at patches that add more verbose logging or open the socket at jenkins start time.

Also, I really need to point folks to https://github.com/openstack-infra/zmq-event-publisher this particular repo isn't the canonical source anymore and since we didn't fork it in github it doesn't show up anywhere here.

**Comment by brejoc** [comment]
Oh - okay, I misunderstood the README. Thanks for the clarification. Is there sample code somewhere available? Seems like I can't subscript to the server with zmq.SUB from my python-zmq-script.

Perhaps you should update the README, so that it points to the new repo. But the guthub-repo from OpenStack has no issue tracker enabled. I guess the official issue tracker and mailing list from OpenStack should be used?

**Comment by cboylan** [comment]
Yup the issue tracker for the OpenStack repo is https://bugs.launchpad.net/openstack-ci. Feel free to submit bugs there and I am slowly getting on top of this and documenting it better. Will push an update to the README on this repo and propose a change to the other repo to include bug info.

**Comment by brejoc** [comment]
Cleaning up. If you think this should be re-opened, feel free to do so or contact me.
